import Head from 'next/head'
import { collection, getDocs, query, where } from 'firebase/firestore';
import db from '../api/clientApp'
import Header from '@/components/Header';
import { Recipe } from '@/types/Recipe';
import { useContext } from 'react';
import { AppContext } from '@/context/state';

export default function RecipePage({name, ingredients, instructions}: Recipe) {

    const appContext = useContext(AppContext)
    appContext.setRecipeName(name)




    return (
        <>
            <Head>
                <title>The Recipes Only</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header/>
            <main className='flex flex-col p-6 min-h-screen  bg-page-bg dark:bg-gray-dark'>
                <div className='border-t border-gray-50 py-1'></div>
                <div className=' sans sm:w-3/5 w-full mx-auto'>
                    <h1 className='text-2xl py-4'>Ingredients</h1>
                    <ul>
                    {ingredients?.map((ingredient:string, i:number) => {
                        return <li key={i}>{ingredient}</li>
                        })}
                    </ul>
                    <h1 className='text-2xl py-4'>Directions</h1>
                    <ol>
                    {instructions?.map((ingredient:string, i:number) => {
                        return <li key={i}>{ingredient}</li>
                        })}
                    </ol>
                </div>
            </main>
        </>
    )
}

export async function getStaticProps(context: any) {
    try {
        const recipesRef = collection(db, "recipes");
        const q = query(recipesRef, where("name", "==", context.params.id));
        const querySnapshot = await getDocs(q);
        const temp = querySnapshot.docs.map(doc => doc.data())
        
        return { 
            props:  temp[0],
            revalidate: 1000000
        }
    } catch (err) {
        console.log(err)
    }
}

export async function getStaticPaths() {
    // call the API to get all the recipes
    const recipesRef = collection(db, "recipes");
    const querySnapshot = await getDocs(recipesRef);
    const temp = querySnapshot.docs.map(doc => doc.data())
    console.log('get Static paths', temp[0].name)
    return {
        paths: [{params: {id: temp[0].name}}],
        fallback: true // false or 'blocking'
    };
}