import Head from 'next/head'
import { collection, getDocs, query, where } from 'firebase/firestore';
import db from '../api/clientApp'
import Header from '@/components/Header';

interface RecipePageProps {
    recipe: {
        name: string
        ingredients: string[]
        instructions: string[]
    }
}
export default function RecipePage({ recipe }: RecipePageProps) {
    return (
        <>
            <Head>
                <title>The Recipes Only</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header/>
            <main className='flex flex-col p-6 min-h-screen  bg-page-bg dark:bg-gray-dark'>
                <div className='border-t border-gray-50 py-1'></div>
                <div className=' sans w-2/5 mx-auto'>
                    <h1 className='text-2xl py-4'>Ingredients</h1>
                    {/* Not using a UL will hurt seo, this is MVP */}
                    <p className='pb-3'>
                        {recipe.ingredients}
                    </p>
                    <h1 className='text-2xl py-4'>Directions</h1>
                    <p>
                        {recipe.instructions}
                    </p>
                </div>
            </main>
        </>
    )
}

export async function getStaticProps(context: any) {
    try {
        const recipesRef = collection(db, "recipes");
        const q = query(recipesRef, where("name", "==", context.params.id));
        const querySnapshot = await getDocs(q);
        const temp = querySnapshot.docs.map(doc => doc.data())
        return { props: { recipe: temp[0]} }
    } catch (err) {
        console.log(err)
    }
}

export async function getStaticPaths() {
    return {
        paths: [
            { params: { id: "STRING", message: "HELLO!" } }
        ],
        fallback: true // false or 'blocking'
    };
}