import Header from "@/components/Header";
import Head from 'next/head'
import { Recipe } from "@/types/Recipe";
import { useEffect, useState } from "react";
import { doc, setDoc } from "firebase/firestore";
import db from "../api/clientApp";
import { capitalizeFirstLetter } from "@/utils/utils";
import { getRecipeApi } from "../api/getRecipe";
import { useRouter } from "next/router";


export default function NewRecipe (props:any) {
    const [recipe, setRecipe] = useState({} as Recipe)
    const [searchTerm, setSearchTerm] = useState('')
    const router = useRouter()
    
    // get the recipe   
    const handleFetch = async () => {
        const prompt = encodeURI(`recipe for ${searchTerm} with ingredients and instructions only`)
        const recipeResponse = await getRecipeApi(prompt)
        return await recipeResponse
    }

    useEffect(() => {
        const {searchTerm} = router.query
        setSearchTerm(searchTerm as string)
    }, [router.query, searchTerm])

    useEffect(() => {
        
        const recipeReturn = handleFetch().then((response) => {
            let newRecipe = {} as Recipe
            console.log('response Text', response)
            newRecipe.ingredients = response.split(/ingredients/i)[0]
            newRecipe.instructions = response.split(/instructions/i)[0]
            newRecipe.name = searchTerm
            setRecipe(newRecipe)
            return {newRecipe}
        })
        
        console.log('new Recipe',  recipeReturn)
    }, [ searchTerm])

    useEffect(() => {
        if(recipe.name){
            console.log('recipe', recipe, recipe.name)
            // save recipe to firestore db
            recipe.name = capitalizeFirstLetter(recipe.name)
            setDoc(doc(db, "recipes", recipe.name), recipe)
            console.log('saving to DB recipe', recipe)
        }

    }, [recipe])

    return(<>
            <Head>
                <title>The Recipes Only</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        <Header/>
        <main className='flex flex-col p-6 min-h-screen  bg-page-bg dark:bg-gray-dark'>
                <div className='border-t border-gray-50 py-1'></div>
                <div className=' sans w-2/5 mx-auto'>
                    <h1 className='text-2xl py-4'>Ingredients</h1>
                    {/* Not using a UL will hurt seo, this is MVP */}
                    <p className='pb-3'>
                        {recipe?.ingredients}
                    </p>
                    <h1 className='text-2xl py-4'>Directions</h1>
                    <p>
                        {recipe?.instructions}
                    </p>
                </div>
            </main>
        </>
    )
}