import Head from 'next/head'

export default function RecipePage() {
    return (
        <>
            <Head>
                <title>The Recipes Only</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header>
                <div className='flex justify-start gap-3 bg-page-bg pt-5'>
                    <h1 className='px-6 py-2 text-xl'>The Recipes Only</h1>
                    <input className='rounded border p-1 my-auto' placeholder='Apple Crepe'></input>
                </div>
                
            </header>
            <main className='flex flex-col p-6 min-h-screen bg-page-bg'>
                <div className='border-t border-gray-50 py-1'></div>
                <div className=' sans w-2/5 mx-auto'>
                <h1 className='text-2xl py-4'>Ingredients</h1>
                {/* Not using a UL will hurt seo, this is MVP */}
                <p className='pb-3'>
                    -1 cup all-purpose flour
                    -2 eggs
                    -1/2 cup milk
                    -1/2 cup water
                    -1/4 teaspoon salt
                    -2 tablespoons butter, melted
                    -1 apple, peeled, cored and thinly sliced
                    -1 tablespoon sugar
                    -1/4 teaspoon ground cinnamon
                </p>
                <h1 className='text-2xl py-4'>Directions</h1>
                <p>
                    In a large mixing bowl, whisk together 1 cup of all-purpose flour, 2 eggs, 1/2 cup of milk, 1/2 cup of water, 1/4 teaspoon of salt and 2 tablespoons of melted butter.
                    Heat a large non-stick skillet over medium heat.
                    Dip the apple slices in the batter and place them on the skillet.
                    Sprinkle 1 tablespoon of sugar and 1/4 teaspoon of ground cinnamon over the apples.
                    Cook the crepes for 2 to 3 minutes on each side or until they are golden brown.
                    Serve warm. Enjoy!
                    Note: You can also add other toppings like whipped cream or maple syrup.
                </p>
                </div>
            </main>
        </>
    )
}